version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb:1.7.4-pg12
    ports:
      - "5432:5432/tcp"
    networks:
      - docker_demo-iot-net
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres1234
      POSTGRES_DB: demo_iot
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:7.1.5
    user: grafana
    ports:
      - "3000:3000/tcp"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - docker_demo-iot-net
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./data/grafana:/var/lib/grafana
    user: grafana
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    ports:
      - "1883:1883/tcp"
      # - "9001:9001/tcp"
    networks:
      - docker_demo-iot-net
    deploy:
      restart_policy:
        condition: on-failure
#    volumes:
#      - ./data/mosquitto:/mosquitto
  pgadmin:
    image: biarms/pgadmin4:4.21
    ports:
      - "5050:5050/tcp"
    networks:
      - docker_demo-iot-net
    deploy:
      restart_policy:
        condition: on-failure
  subscriber:
    image: subscribe-mqtt:latest
    networks:
      - docker_demo-iot-net
networks:
  docker_demo-iot-net:
